# coding: utf-8
import argparse
# Autogenerated with DRAKON Editor 1.28

def parse(largs):
    #item 21
    import argparse
    objet_parser = argparse.ArgumentParser()
    objet_subparsers = objet_parser.add_subparsers()
    #item 47
    #gui DOIT exister dans le namespace, donc etre initialisee
    #  init à une valeur d attente vaut faux ou none
    objet_parser.add_argument('--gui',  default=False, dest="gui")
    # fichier doit
    objet_parser.add_argument('--file',  default=False, dest="file" )
    #item 24
    objet_parser_ligne = objet_subparsers.add_parser('ligne')
    objet_parser_ligne.add_argument('jours')
    objet_parser_ligne.add_argument('mois')
    objet_parser_ligne.add_argument('annee')
    objet_parser_ligne.add_argument('poste')
    #item 25
    objet_parser_gui = objet_subparsers.add_parser('gui')
    objet_parser_gui.add_argument("-g", "--gui", action="store_true", help="mode graphique", dest="gui", default=True)
    #item 35
    objet_parser_file = objet_subparsers.add_parser('fileparse')
    objet_parser_file.add_argument("-f", "--file", action="store", help="mode fichier", dest="file")
    #item 23
    return objet_parser.parse_args(largs)

    pass

